name = "ModifiedDistributions"
uuid = "664e6f8c-d74f-44d3-9f37-f82699103046"
authors = ["Sam Abbott", "EpiAware contributors"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
DocStringExtensions = "0.9"
julia = "1.10, 1.11, 1.12"

[workspace]
projects = ["test", "docs"]
