name = "ModifiedDistributions"
uuid = "664e6f8c-d74f-44d3-9f37-f82699103046"
authors = ["Sam Abbott", "EpiAware contributors"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[weakdeps]
ComposedDistributions = "2f642b71-32a9-4f47-97c4-6deb7517f7a7"
ConvolvedDistributions = "f5b942c9-bc5b-4664-8486-7f531bb06742"

[extensions]
ModifiedDistributionsComposedDistributionsExt = "ComposedDistributions"
ModifiedDistributionsConvolvedDistributionsExt = "ConvolvedDistributions"

[compat]
ComposedDistributions = "0.1"
ConvolvedDistributions = "0.2"
Distributions = "0.25"
DocStringExtensions = "0.9"
Random = "1"
Test = "1"
julia = "1.11, 1.12"

[workspace]
projects = ["test", "docs"]
