# PACKAGE-OWNED — scaffold writes this once and never overwrites it.
# The docs navigation tree. Add tutorial / guide pages here as the package
# grows; `make.jl` reads `pages` from this file. The API reference and the
# README-derived home page are generated by `make.jl`.
#
# The Benchmarks entry below is written only when the package is scaffolded with
# `benchmarks = true` (it is the `` substitution); a package
# without benchmarks gets no entry and no page.

pages = [
    "Home" => "index.md",
    # Authored quickstart + infrastructure guide (package-owned source pages,
    # distinct from the README-derived home page). Add tutorials under
    # `getting-started/` as the package grows.
    "Getting started" => [
        "Overview" => "getting-started/index.md",
        "Infrastructure and template sync" => "getting-started/infrastructure.md",
        "Customising your docs" => "getting-started/customising.md"
    ],
    "API reference" => [
        "Public API" => "lib/public.md",
        "Internal API" => "lib/internals.md"
    ]
]
